import Head from "next/head";
import { FoodCateCrud } from "@/components/foodcatecrud/FoodCateCrud";
import { Container, Stack } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Delivery Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack
          width={"100%"}
          sx={{ backgroundColor: "#FFF" }}
          alignItems={"flex-start"}
          paddingTop={"100px"}
          bgcolor={""}
          height={"content"}
        >
          <Container maxWidth={"xl"} sx={{ width: "1306px" }}>
            <Stack gap={"30px"}>
              <FoodCateCrud />
            </Stack>
          </Container>
        </Stack>
      </main>
    </>
  );
}
